package cn.livedoor.security.sysguard.domain;

public class ApplogExample extends Applog {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int applogId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int userId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int hostId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int level_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int uptime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int className_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int threadName_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int logTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int logLine_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int logContent_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int logStatus_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int solveTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int solveResult_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int solveDesc_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int inputTime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getApplogId_Indicator() {
	return applogId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setApplogId_Indicator(int applogId_Indicator) {
	this.applogId_Indicator = applogId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getUserId_Indicator() {
	return userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUserId_Indicator(int userId_Indicator) {
	this.userId_Indicator = userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getHostId_Indicator() {
	return hostId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setHostId_Indicator(int hostId_Indicator) {
	this.hostId_Indicator = hostId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLevel_Indicator() {
	return level_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLevel_Indicator(int level_Indicator) {
	this.level_Indicator = level_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getUptime_Indicator() {
	return uptime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUptime_Indicator(int uptime_Indicator) {
	this.uptime_Indicator = uptime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getClassName_Indicator() {
	return className_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setClassName_Indicator(int className_Indicator) {
	this.className_Indicator = className_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getThreadName_Indicator() {
	return threadName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setThreadName_Indicator(int threadName_Indicator) {
	this.threadName_Indicator = threadName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLogTime_Indicator() {
	return logTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLogTime_Indicator(int logTime_Indicator) {
	this.logTime_Indicator = logTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLogLine_Indicator() {
	return logLine_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLogLine_Indicator(int logLine_Indicator) {
	this.logLine_Indicator = logLine_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLogContent_Indicator() {
	return logContent_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLogContent_Indicator(int logContent_Indicator) {
	this.logContent_Indicator = logContent_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLogStatus_Indicator() {
	return logStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLogStatus_Indicator(int logStatus_Indicator) {
	this.logStatus_Indicator = logStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getSolveTime_Indicator() {
	return solveTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setSolveTime_Indicator(int solveTime_Indicator) {
	this.solveTime_Indicator = solveTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getSolveResult_Indicator() {
	return solveResult_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setSolveResult_Indicator(int solveResult_Indicator) {
	this.solveResult_Indicator = solveResult_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getSolveDesc_Indicator() {
	return solveDesc_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setSolveDesc_Indicator(int solveDesc_Indicator) {
	this.solveDesc_Indicator = solveDesc_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getInputTime_Indicator() {
	return inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime_Indicator(int inputTime_Indicator) {
	this.inputTime_Indicator = inputTime_Indicator;
    }
}