package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class OsType {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column os_type.os_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer osId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column os_type.os_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String osName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column os_type.description
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String description;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column os_type.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Date inputTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column os_type.os_id
     * @return  the value of os_type.os_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getOsId() {
	return osId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column os_type.os_id
     * @param osId  the value for os_type.os_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOsId(Integer osId) {
	this.osId = osId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column os_type.os_name
     * @return  the value of os_type.os_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getOsName() {
	return osName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column os_type.os_name
     * @param osName  the value for os_type.os_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOsName(String osName) {
	this.osName = osName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column os_type.description
     * @return  the value of os_type.description
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getDescription() {
	return description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column os_type.description
     * @param description  the value for os_type.description
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setDescription(String description) {
	this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column os_type.input_time
     * @return  the value of os_type.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column os_type.input_time
     * @param inputTime  the value for os_type.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }
}