package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class User {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.user_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer userId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.role_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer roleId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String name;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.real_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String realName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.passwd
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String passwd;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.mail
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String mail;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.msn
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String msn;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.skype
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String skype;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.last_login_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Date lastLoginTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.online
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Byte online;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.validate
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Byte validate;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Date inputTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user.update_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Date updateTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.user_id
     * @return  the value of user.user_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getUserId() {
	return userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.user_id
     * @param userId  the value for user.user_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUserId(Integer userId) {
	this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.role_id
     * @return  the value of user.role_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getRoleId() {
	return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.role_id
     * @param roleId  the value for user.role_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setRoleId(Integer roleId) {
	this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.name
     * @return  the value of user.name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getName() {
	return name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.name
     * @param name  the value for user.name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setName(String name) {
	this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.real_name
     * @return  the value of user.real_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getRealName() {
	return realName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.real_name
     * @param realName  the value for user.real_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setRealName(String realName) {
	this.realName = realName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.passwd
     * @return  the value of user.passwd
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getPasswd() {
	return passwd;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.passwd
     * @param passwd  the value for user.passwd
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setPasswd(String passwd) {
	this.passwd = passwd;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.mail
     * @return  the value of user.mail
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getMail() {
	return mail;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.mail
     * @param mail  the value for user.mail
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setMail(String mail) {
	this.mail = mail;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.msn
     * @return  the value of user.msn
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getMsn() {
	return msn;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.msn
     * @param msn  the value for user.msn
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setMsn(String msn) {
	this.msn = msn;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.skype
     * @return  the value of user.skype
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getSkype() {
	return skype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.skype
     * @param skype  the value for user.skype
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setSkype(String skype) {
	this.skype = skype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.last_login_time
     * @return  the value of user.last_login_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Date getLastLoginTime() {
	return lastLoginTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.last_login_time
     * @param lastLoginTime  the value for user.last_login_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLastLoginTime(Date lastLoginTime) {
	this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.online
     * @return  the value of user.online
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Byte getOnline() {
	return online;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.online
     * @param online  the value for user.online
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOnline(Byte online) {
	this.online = online;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.validate
     * @return  the value of user.validate
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Byte getValidate() {
	return validate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.validate
     * @param validate  the value for user.validate
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setValidate(Byte validate) {
	this.validate = validate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.input_time
     * @return  the value of user.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.input_time
     * @param inputTime  the value for user.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user.update_time
     * @return  the value of user.update_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Date getUpdateTime() {
	return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user.update_time
     * @param updateTime  the value for user.update_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUpdateTime(Date updateTime) {
	this.updateTime = updateTime;
    }
}