package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.DataInfo;
import cn.livedoor.security.sysguard.domain.DataInfoExample;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import cn.livedoor.security.sysguard.domain.DataInfoKey;

public class DataInfoDAOImpl extends SqlMapDaoTemplate implements DataInfoDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public DataInfoDAOImpl(DaoManager daoManager) {
	super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void insert(DataInfo record) {
	insert("data_info.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKey(DataInfo record) {
	int rows = update("data_info.abatorgenerated_updateByPrimaryKey", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKeySelective(DataInfo record) {
	int rows = update("data_info.abatorgenerated_updateByPrimaryKeySelective", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(DataInfoExample example, String orderByClause) {
	Map parms = getExampleParms(example);
	if (orderByClause != null) {
	    parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
	}
	List list = queryForList("data_info.abatorgenerated_selectByExample", parms);
	return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(DataInfoExample example) {
	return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public DataInfo selectByPrimaryKey(DataInfoKey key) {
	DataInfo record = (DataInfo) queryForObject("data_info.abatorgenerated_selectByPrimaryKey", key);
	return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByExample(DataInfoExample example) {
	int rows = delete("data_info.abatorgenerated_deleteByExample", getExampleParms(example));
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByPrimaryKey(DataInfoKey key) {
	int rows = delete("data_info.abatorgenerated_deleteByPrimaryKey", key);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map gethost_idExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	switch (example.getHostId_Indicator()) {
	case DataInfoExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NULL", "Y");
	    } else {
		parms.put("AND_host_id_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_host_id_NOT_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_EQUALS", "Y");
	    } else {
		parms.put("AND_host_id_EQUALS", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case DataInfoExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_host_id_NOT_EQUALS", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_GT", "Y");
	    } else {
		parms.put("AND_host_id_GT", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_GE", "Y");
	    } else {
		parms.put("AND_host_id_GE", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_LT", "Y");
	    } else {
		parms.put("AND_host_id_LT", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_LE", "Y");
	    } else {
		parms.put("AND_host_id_LE", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map gettype_idExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	switch (example.getTypeId_Indicator()) {
	case DataInfoExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_NULL", "Y");
	    } else {
		parms.put("AND_type_id_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_type_id_NOT_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_EQUALS", "Y");
	    } else {
		parms.put("AND_type_id_EQUALS", "Y");
	    }
	    parms.put("typeId", example.getTypeId());
	    break;
	case DataInfoExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_type_id_NOT_EQUALS", "Y");
	    }
	    parms.put("typeId", example.getTypeId());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_GT", "Y");
	    } else {
		parms.put("AND_type_id_GT", "Y");
	    }
	    parms.put("typeId", example.getTypeId());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_GE", "Y");
	    } else {
		parms.put("AND_type_id_GE", "Y");
	    }
	    parms.put("typeId", example.getTypeId());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_LT", "Y");
	    } else {
		parms.put("AND_type_id_LT", "Y");
	    }
	    parms.put("typeId", example.getTypeId());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_type_id_LE", "Y");
	    } else {
		parms.put("AND_type_id_LE", "Y");
	    }
	    parms.put("typeId", example.getTypeId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getvalue1ExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	switch (example.getValue1_Indicator()) {
	case DataInfoExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_NULL", "Y");
	    } else {
		parms.put("AND_value1_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_NOT_NULL", "Y");
	    } else {
		parms.put("AND_value1_NOT_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_EQUALS", "Y");
	    } else {
		parms.put("AND_value1_EQUALS", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	case DataInfoExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_value1_NOT_EQUALS", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_GT", "Y");
	    } else {
		parms.put("AND_value1_GT", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_GE", "Y");
	    } else {
		parms.put("AND_value1_GE", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_LT", "Y");
	    } else {
		parms.put("AND_value1_LT", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_LE", "Y");
	    } else {
		parms.put("AND_value1_LE", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	case DataInfoExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value1_LIKE", "Y");
	    } else {
		parms.put("AND_value1_LIKE", "Y");
	    }
	    parms.put("value1", example.getValue1());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getvalue2ExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	switch (example.getValue2_Indicator()) {
	case DataInfoExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_NULL", "Y");
	    } else {
		parms.put("AND_value2_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_NOT_NULL", "Y");
	    } else {
		parms.put("AND_value2_NOT_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_EQUALS", "Y");
	    } else {
		parms.put("AND_value2_EQUALS", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	case DataInfoExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_value2_NOT_EQUALS", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_GT", "Y");
	    } else {
		parms.put("AND_value2_GT", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_GE", "Y");
	    } else {
		parms.put("AND_value2_GE", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_LT", "Y");
	    } else {
		parms.put("AND_value2_LT", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_LE", "Y");
	    } else {
		parms.put("AND_value2_LE", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	case DataInfoExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value2_LIKE", "Y");
	    } else {
		parms.put("AND_value2_LIKE", "Y");
	    }
	    parms.put("value2", example.getValue2());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getvalue3ExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	switch (example.getValue3_Indicator()) {
	case DataInfoExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_NULL", "Y");
	    } else {
		parms.put("AND_value3_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_NOT_NULL", "Y");
	    } else {
		parms.put("AND_value3_NOT_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_EQUALS", "Y");
	    } else {
		parms.put("AND_value3_EQUALS", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	case DataInfoExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_value3_NOT_EQUALS", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_GT", "Y");
	    } else {
		parms.put("AND_value3_GT", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_GE", "Y");
	    } else {
		parms.put("AND_value3_GE", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_LT", "Y");
	    } else {
		parms.put("AND_value3_LT", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_LE", "Y");
	    } else {
		parms.put("AND_value3_LE", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	case DataInfoExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_value3_LIKE", "Y");
	    } else {
		parms.put("AND_value3_LIKE", "Y");
	    }
	    parms.put("value3", example.getValue3());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getinput_timeExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	switch (example.getInputTime_Indicator()) {
	case DataInfoExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NOT_NULL", "Y");
	    }
	    break;
	case DataInfoExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case DataInfoExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_NOT_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GT", "Y");
	    } else {
		parms.put("AND_input_time_GT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case DataInfoExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GE", "Y");
	    } else {
		parms.put("AND_input_time_GE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LT", "Y");
	    } else {
		parms.put("AND_input_time_LT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case DataInfoExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LE", "Y");
	    } else {
		parms.put("AND_input_time_LE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getExampleParms(DataInfoExample example) {
	Map parms = new HashMap();
	parms.putAll(gethost_idExampleParms(example));
	parms.putAll(gettype_idExampleParms(example));
	parms.putAll(getvalue1ExampleParms(example));
	parms.putAll(getvalue2ExampleParms(example));
	parms.putAll(getvalue3ExampleParms(example));
	parms.putAll(getinput_timeExampleParms(example));
	return parms;
    }
}