package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.HostGroup;
import cn.livedoor.security.sysguard.domain.HostGroupExample;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HostGroupDAOImpl extends SqlMapDaoTemplate implements HostGroupDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public HostGroupDAOImpl(DaoManager daoManager) {
	super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void insert(HostGroup record) {
	insert("host_group.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int updateByPrimaryKey(HostGroup record) {
	int rows = update("host_group.abatorgenerated_updateByPrimaryKey", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int updateByPrimaryKeySelective(HostGroup record) {
	int rows = update("host_group.abatorgenerated_updateByPrimaryKeySelective", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public List selectByExample(HostGroupExample example, String orderByClause) {
	Map parms = getExampleParms(example);
	if (orderByClause != null) {
	    parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
	}
	List list = queryForList("host_group.abatorgenerated_selectByExample", parms);
	return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public List selectByExample(HostGroupExample example) {
	return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public HostGroup selectByPrimaryKey(Integer groupId) {
	HostGroup key = new HostGroup();
	key.setGroupId(groupId);
	HostGroup record = (HostGroup) queryForObject("host_group.abatorgenerated_selectByPrimaryKey", key);
	return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int deleteByExample(HostGroupExample example) {
	int rows = delete("host_group.abatorgenerated_deleteByExample", getExampleParms(example));
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int deleteByPrimaryKey(Integer groupId) {
	HostGroup key = new HostGroup();
	key.setGroupId(groupId);
	int rows = delete("host_group.abatorgenerated_deleteByPrimaryKey", key);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getgroup_idExampleParms(HostGroupExample example) {
	Map parms = new HashMap();
	switch (example.getGroupId_Indicator()) {
	case HostGroupExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_NULL", "Y");
	    } else {
		parms.put("AND_group_id_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_group_id_NOT_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_EQUALS", "Y");
	    } else {
		parms.put("AND_group_id_EQUALS", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostGroupExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_group_id_NOT_EQUALS", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_GT", "Y");
	    } else {
		parms.put("AND_group_id_GT", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_GE", "Y");
	    } else {
		parms.put("AND_group_id_GE", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_LT", "Y");
	    } else {
		parms.put("AND_group_id_LT", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_LE", "Y");
	    } else {
		parms.put("AND_group_id_LE", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getos_idExampleParms(HostGroupExample example) {
	Map parms = new HashMap();
	switch (example.getOsId_Indicator()) {
	case HostGroupExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_NULL", "Y");
	    } else {
		parms.put("AND_os_id_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_os_id_NOT_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_EQUALS", "Y");
	    } else {
		parms.put("AND_os_id_EQUALS", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case HostGroupExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_os_id_NOT_EQUALS", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_GT", "Y");
	    } else {
		parms.put("AND_os_id_GT", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_GE", "Y");
	    } else {
		parms.put("AND_os_id_GE", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_LT", "Y");
	    } else {
		parms.put("AND_os_id_LT", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_LE", "Y");
	    } else {
		parms.put("AND_os_id_LE", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getgroup_nameExampleParms(HostGroupExample example) {
	Map parms = new HashMap();
	switch (example.getGroupName_Indicator()) {
	case HostGroupExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_NULL", "Y");
	    } else {
		parms.put("AND_group_name_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_group_name_NOT_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_EQUALS", "Y");
	    } else {
		parms.put("AND_group_name_EQUALS", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	case HostGroupExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_group_name_NOT_EQUALS", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_GT", "Y");
	    } else {
		parms.put("AND_group_name_GT", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_GE", "Y");
	    } else {
		parms.put("AND_group_name_GE", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_LT", "Y");
	    } else {
		parms.put("AND_group_name_LT", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_LE", "Y");
	    } else {
		parms.put("AND_group_name_LE", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	case HostGroupExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_name_LIKE", "Y");
	    } else {
		parms.put("AND_group_name_LIKE", "Y");
	    }
	    parms.put("groupName", example.getGroupName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getdescriptionExampleParms(HostGroupExample example) {
	Map parms = new HashMap();
	switch (example.getDescription_Indicator()) {
	case HostGroupExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NULL", "Y");
	    } else {
		parms.put("AND_description_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_NULL", "Y");
	    } else {
		parms.put("AND_description_NOT_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_EQUALS", "Y");
	    } else {
		parms.put("AND_description_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostGroupExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_description_NOT_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GT", "Y");
	    } else {
		parms.put("AND_description_GT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GE", "Y");
	    } else {
		parms.put("AND_description_GE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LT", "Y");
	    } else {
		parms.put("AND_description_LT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LE", "Y");
	    } else {
		parms.put("AND_description_LE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostGroupExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LIKE", "Y");
	    } else {
		parms.put("AND_description_LIKE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getinput_timeExampleParms(HostGroupExample example) {
	Map parms = new HashMap();
	switch (example.getInputTime_Indicator()) {
	case HostGroupExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NOT_NULL", "Y");
	    }
	    break;
	case HostGroupExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostGroupExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_NOT_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GT", "Y");
	    } else {
		parms.put("AND_input_time_GT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostGroupExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GE", "Y");
	    } else {
		parms.put("AND_input_time_GE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LT", "Y");
	    } else {
		parms.put("AND_input_time_LT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostGroupExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LE", "Y");
	    } else {
		parms.put("AND_input_time_LE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host_group
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getExampleParms(HostGroupExample example) {
	Map parms = new HashMap();
	parms.putAll(getgroup_idExampleParms(example));
	parms.putAll(getos_idExampleParms(example));
	parms.putAll(getgroup_nameExampleParms(example));
	parms.putAll(getdescriptionExampleParms(example));
	parms.putAll(getinput_timeExampleParms(example));
	return parms;
    }
}