package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.OsType;
import cn.livedoor.security.sysguard.domain.OsTypeExample;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OsTypeDAOImpl extends SqlMapDaoTemplate implements OsTypeDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public OsTypeDAOImpl(DaoManager daoManager) {
	super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void insert(OsType record) {
	insert("os_type.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int updateByPrimaryKey(OsType record) {
	int rows = update("os_type.abatorgenerated_updateByPrimaryKey", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int updateByPrimaryKeySelective(OsType record) {
	int rows = update("os_type.abatorgenerated_updateByPrimaryKeySelective", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public List selectByExample(OsTypeExample example, String orderByClause) {
	Map parms = getExampleParms(example);
	if (orderByClause != null) {
	    parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
	}
	List list = queryForList("os_type.abatorgenerated_selectByExample", parms);
	return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public List selectByExample(OsTypeExample example) {
	return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public OsType selectByPrimaryKey(Integer osId) {
	OsType key = new OsType();
	key.setOsId(osId);
	OsType record = (OsType) queryForObject("os_type.abatorgenerated_selectByPrimaryKey", key);
	return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int deleteByExample(OsTypeExample example) {
	int rows = delete("os_type.abatorgenerated_deleteByExample", getExampleParms(example));
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public int deleteByPrimaryKey(Integer osId) {
	OsType key = new OsType();
	key.setOsId(osId);
	int rows = delete("os_type.abatorgenerated_deleteByPrimaryKey", key);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getos_idExampleParms(OsTypeExample example) {
	Map parms = new HashMap();
	switch (example.getOsId_Indicator()) {
	case OsTypeExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_NULL", "Y");
	    } else {
		parms.put("AND_os_id_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_os_id_NOT_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_EQUALS", "Y");
	    } else {
		parms.put("AND_os_id_EQUALS", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case OsTypeExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_os_id_NOT_EQUALS", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_GT", "Y");
	    } else {
		parms.put("AND_os_id_GT", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_GE", "Y");
	    } else {
		parms.put("AND_os_id_GE", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_LT", "Y");
	    } else {
		parms.put("AND_os_id_LT", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_id_LE", "Y");
	    } else {
		parms.put("AND_os_id_LE", "Y");
	    }
	    parms.put("osId", example.getOsId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getos_nameExampleParms(OsTypeExample example) {
	Map parms = new HashMap();
	switch (example.getOsName_Indicator()) {
	case OsTypeExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_NULL", "Y");
	    } else {
		parms.put("AND_os_name_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_os_name_NOT_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_EQUALS", "Y");
	    } else {
		parms.put("AND_os_name_EQUALS", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	case OsTypeExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_os_name_NOT_EQUALS", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_GT", "Y");
	    } else {
		parms.put("AND_os_name_GT", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_GE", "Y");
	    } else {
		parms.put("AND_os_name_GE", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_LT", "Y");
	    } else {
		parms.put("AND_os_name_LT", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_LE", "Y");
	    } else {
		parms.put("AND_os_name_LE", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	case OsTypeExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_os_name_LIKE", "Y");
	    } else {
		parms.put("AND_os_name_LIKE", "Y");
	    }
	    parms.put("osName", example.getOsName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getdescriptionExampleParms(OsTypeExample example) {
	Map parms = new HashMap();
	switch (example.getDescription_Indicator()) {
	case OsTypeExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NULL", "Y");
	    } else {
		parms.put("AND_description_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_NULL", "Y");
	    } else {
		parms.put("AND_description_NOT_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_EQUALS", "Y");
	    } else {
		parms.put("AND_description_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case OsTypeExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_description_NOT_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GT", "Y");
	    } else {
		parms.put("AND_description_GT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GE", "Y");
	    } else {
		parms.put("AND_description_GE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LT", "Y");
	    } else {
		parms.put("AND_description_LT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LE", "Y");
	    } else {
		parms.put("AND_description_LE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case OsTypeExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LIKE", "Y");
	    } else {
		parms.put("AND_description_LIKE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getinput_timeExampleParms(OsTypeExample example) {
	Map parms = new HashMap();
	switch (example.getInputTime_Indicator()) {
	case OsTypeExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NOT_NULL", "Y");
	    }
	    break;
	case OsTypeExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case OsTypeExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_NOT_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GT", "Y");
	    } else {
		parms.put("AND_input_time_GT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case OsTypeExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GE", "Y");
	    } else {
		parms.put("AND_input_time_GE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LT", "Y");
	    } else {
		parms.put("AND_input_time_LT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case OsTypeExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LE", "Y");
	    } else {
		parms.put("AND_input_time_LE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Map getExampleParms(OsTypeExample example) {
	Map parms = new HashMap();
	parms.putAll(getos_idExampleParms(example));
	parms.putAll(getos_nameExampleParms(example));
	parms.putAll(getdescriptionExampleParms(example));
	parms.putAll(getinput_timeExampleParms(example));
	return parms;
    }
}