package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.Host;
import cn.livedoor.security.sysguard.domain.HostExample;
import java.util.List;

public interface HostDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    void insert(Host record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKey(Host record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKeySelective(Host record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExample(HostExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExample(HostExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    Host selectByPrimaryKey(Integer hostId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int deleteByExample(HostExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int deleteByPrimaryKey(Integer hostId);
}