package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.Operation;
import cn.livedoor.security.sysguard.domain.OperationExample;
import cn.livedoor.security.sysguard.domain.OperationWithBLOBs;
import java.util.List;

public interface OperationDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    void insert(OperationWithBLOBs record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKey(Operation record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKey(OperationWithBLOBs record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKeySelective(OperationWithBLOBs record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExampleWithoutBLOBs(OperationExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExampleWithoutBLOBs(OperationExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExampleWithBLOBs(OperationExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExampleWithBLOBs(OperationExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    OperationWithBLOBs selectByPrimaryKey(Integer operId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int deleteByExample(OperationExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table operation
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int deleteByPrimaryKey(Integer operId);
}