package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.OsType;
import cn.livedoor.security.sysguard.domain.OsTypeExample;
import java.util.List;

public interface OsTypeDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    void insert(OsType record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKey(OsType record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int updateByPrimaryKeySelective(OsType record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExample(OsTypeExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    List selectByExample(OsTypeExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    OsType selectByPrimaryKey(Integer osId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int deleteByExample(OsTypeExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    int deleteByPrimaryKey(Integer osId);
}