package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.Host;
import cn.livedoor.security.sysguard.domain.HostExample;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HostDAOImpl extends SqlMapDaoTemplate implements HostDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public HostDAOImpl(DaoManager daoManager) {
	super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void insert(Host record) {
	insert("host.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKey(Host record) {
	int rows = update("host.abatorgenerated_updateByPrimaryKey", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKeySelective(Host record) {
	int rows = update("host.abatorgenerated_updateByPrimaryKeySelective", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(HostExample example, String orderByClause) {
	Map parms = getExampleParms(example);
	if (orderByClause != null) {
	    parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
	}
	List list = queryForList("host.abatorgenerated_selectByExample", parms);
	return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(HostExample example) {
	return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Host selectByPrimaryKey(Integer hostId) {
	Host key = new Host();
	key.setHostId(hostId);
	Host record = (Host) queryForObject("host.abatorgenerated_selectByPrimaryKey", key);
	return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByExample(HostExample example) {
	int rows = delete("host.abatorgenerated_deleteByExample", getExampleParms(example));
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByPrimaryKey(Integer hostId) {
	Host key = new Host();
	key.setHostId(hostId);
	int rows = delete("host.abatorgenerated_deleteByPrimaryKey", key);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map gethost_idExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getHostId_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NULL", "Y");
	    } else {
		parms.put("AND_host_id_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_host_id_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_EQUALS", "Y");
	    } else {
		parms.put("AND_host_id_EQUALS", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_host_id_NOT_EQUALS", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_GT", "Y");
	    } else {
		parms.put("AND_host_id_GT", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_GE", "Y");
	    } else {
		parms.put("AND_host_id_GE", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_LT", "Y");
	    } else {
		parms.put("AND_host_id_LT", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_LE", "Y");
	    } else {
		parms.put("AND_host_id_LE", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getgroup_idExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getGroupId_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_NULL", "Y");
	    } else {
		parms.put("AND_group_id_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_group_id_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_EQUALS", "Y");
	    } else {
		parms.put("AND_group_id_EQUALS", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_group_id_NOT_EQUALS", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_GT", "Y");
	    } else {
		parms.put("AND_group_id_GT", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_GE", "Y");
	    } else {
		parms.put("AND_group_id_GE", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_LT", "Y");
	    } else {
		parms.put("AND_group_id_LT", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_group_id_LE", "Y");
	    } else {
		parms.put("AND_group_id_LE", "Y");
	    }
	    parms.put("groupId", example.getGroupId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map gethost_nameExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getHostName_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_NULL", "Y");
	    } else {
		parms.put("AND_host_name_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_host_name_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_EQUALS", "Y");
	    } else {
		parms.put("AND_host_name_EQUALS", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_host_name_NOT_EQUALS", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_GT", "Y");
	    } else {
		parms.put("AND_host_name_GT", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_GE", "Y");
	    } else {
		parms.put("AND_host_name_GE", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_LT", "Y");
	    } else {
		parms.put("AND_host_name_LT", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_LE", "Y");
	    } else {
		parms.put("AND_host_name_LE", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_name_LIKE", "Y");
	    } else {
		parms.put("AND_host_name_LIKE", "Y");
	    }
	    parms.put("hostName", example.getHostName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map gethost_ipExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getHostIp_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_NULL", "Y");
	    } else {
		parms.put("AND_host_ip_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_NOT_NULL", "Y");
	    } else {
		parms.put("AND_host_ip_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_EQUALS", "Y");
	    } else {
		parms.put("AND_host_ip_EQUALS", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_host_ip_NOT_EQUALS", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_GT", "Y");
	    } else {
		parms.put("AND_host_ip_GT", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_GE", "Y");
	    } else {
		parms.put("AND_host_ip_GE", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_LT", "Y");
	    } else {
		parms.put("AND_host_ip_LT", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_LE", "Y");
	    } else {
		parms.put("AND_host_ip_LE", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_ip_LIKE", "Y");
	    } else {
		parms.put("AND_host_ip_LIKE", "Y");
	    }
	    parms.put("hostIp", example.getHostIp());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlogin_nameExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getLoginName_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_NULL", "Y");
	    } else {
		parms.put("AND_login_name_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_login_name_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_EQUALS", "Y");
	    } else {
		parms.put("AND_login_name_EQUALS", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_login_name_NOT_EQUALS", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_GT", "Y");
	    } else {
		parms.put("AND_login_name_GT", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_GE", "Y");
	    } else {
		parms.put("AND_login_name_GE", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_LT", "Y");
	    } else {
		parms.put("AND_login_name_LT", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_LE", "Y");
	    } else {
		parms.put("AND_login_name_LE", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_name_LIKE", "Y");
	    } else {
		parms.put("AND_login_name_LIKE", "Y");
	    }
	    parms.put("loginName", example.getLoginName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlogin_pwdExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getLoginPwd_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_NULL", "Y");
	    } else {
		parms.put("AND_login_pwd_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_NOT_NULL", "Y");
	    } else {
		parms.put("AND_login_pwd_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_EQUALS", "Y");
	    } else {
		parms.put("AND_login_pwd_EQUALS", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_login_pwd_NOT_EQUALS", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_GT", "Y");
	    } else {
		parms.put("AND_login_pwd_GT", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_GE", "Y");
	    } else {
		parms.put("AND_login_pwd_GE", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_LT", "Y");
	    } else {
		parms.put("AND_login_pwd_LT", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_LE", "Y");
	    } else {
		parms.put("AND_login_pwd_LE", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_login_pwd_LIKE", "Y");
	    } else {
		parms.put("AND_login_pwd_LIKE", "Y");
	    }
	    parms.put("loginPwd", example.getLoginPwd());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getdiskPartitionExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getDiskpartition_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_NULL", "Y");
	    } else {
		parms.put("AND_diskPartition_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_NOT_NULL", "Y");
	    } else {
		parms.put("AND_diskPartition_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_EQUALS", "Y");
	    } else {
		parms.put("AND_diskPartition_EQUALS", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_diskPartition_NOT_EQUALS", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_GT", "Y");
	    } else {
		parms.put("AND_diskPartition_GT", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_GE", "Y");
	    } else {
		parms.put("AND_diskPartition_GE", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_LT", "Y");
	    } else {
		parms.put("AND_diskPartition_LT", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_LE", "Y");
	    } else {
		parms.put("AND_diskPartition_LE", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_diskPartition_LIKE", "Y");
	    } else {
		parms.put("AND_diskPartition_LIKE", "Y");
	    }
	    parms.put("diskpartition", example.getDiskpartition());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getuptimeExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getUptime_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_NULL", "Y");
	    } else {
		parms.put("AND_uptime_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_NOT_NULL", "Y");
	    } else {
		parms.put("AND_uptime_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_EQUALS", "Y");
	    } else {
		parms.put("AND_uptime_EQUALS", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_uptime_NOT_EQUALS", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_GT", "Y");
	    } else {
		parms.put("AND_uptime_GT", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_GE", "Y");
	    } else {
		parms.put("AND_uptime_GE", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_LT", "Y");
	    } else {
		parms.put("AND_uptime_LT", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_LE", "Y");
	    } else {
		parms.put("AND_uptime_LE", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_LIKE", "Y");
	    } else {
		parms.put("AND_uptime_LIKE", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getdescriptionExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getDescription_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NULL", "Y");
	    } else {
		parms.put("AND_description_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_NULL", "Y");
	    } else {
		parms.put("AND_description_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_EQUALS", "Y");
	    } else {
		parms.put("AND_description_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_description_NOT_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GT", "Y");
	    } else {
		parms.put("AND_description_GT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GE", "Y");
	    } else {
		parms.put("AND_description_GE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LT", "Y");
	    } else {
		parms.put("AND_description_LT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LE", "Y");
	    } else {
		parms.put("AND_description_LE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case HostExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LIKE", "Y");
	    } else {
		parms.put("AND_description_LIKE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getvalidateExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getValidate_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_NULL", "Y");
	    } else {
		parms.put("AND_validate_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_NOT_NULL", "Y");
	    } else {
		parms.put("AND_validate_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_EQUALS", "Y");
	    } else {
		parms.put("AND_validate_EQUALS", "Y");
	    }
	    parms.put("validate", example.getValidate());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_validate_NOT_EQUALS", "Y");
	    }
	    parms.put("validate", example.getValidate());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_GT", "Y");
	    } else {
		parms.put("AND_validate_GT", "Y");
	    }
	    parms.put("validate", example.getValidate());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_GE", "Y");
	    } else {
		parms.put("AND_validate_GE", "Y");
	    }
	    parms.put("validate", example.getValidate());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_LT", "Y");
	    } else {
		parms.put("AND_validate_LT", "Y");
	    }
	    parms.put("validate", example.getValidate());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_validate_LE", "Y");
	    } else {
		parms.put("AND_validate_LE", "Y");
	    }
	    parms.put("validate", example.getValidate());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getinput_timeExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getInputTime_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_NOT_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GT", "Y");
	    } else {
		parms.put("AND_input_time_GT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GE", "Y");
	    } else {
		parms.put("AND_input_time_GE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LT", "Y");
	    } else {
		parms.put("AND_input_time_LT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LE", "Y");
	    } else {
		parms.put("AND_input_time_LE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getupdate_timeExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getUpdateTime_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_NULL", "Y");
	    } else {
		parms.put("AND_update_time_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_update_time_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_EQUALS", "Y");
	    } else {
		parms.put("AND_update_time_EQUALS", "Y");
	    }
	    parms.put("updateTime", example.getUpdateTime());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_update_time_NOT_EQUALS", "Y");
	    }
	    parms.put("updateTime", example.getUpdateTime());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_GT", "Y");
	    } else {
		parms.put("AND_update_time_GT", "Y");
	    }
	    parms.put("updateTime", example.getUpdateTime());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_GE", "Y");
	    } else {
		parms.put("AND_update_time_GE", "Y");
	    }
	    parms.put("updateTime", example.getUpdateTime());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_LT", "Y");
	    } else {
		parms.put("AND_update_time_LT", "Y");
	    }
	    parms.put("updateTime", example.getUpdateTime());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_update_time_LE", "Y");
	    } else {
		parms.put("AND_update_time_LE", "Y");
	    }
	    parms.put("updateTime", example.getUpdateTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getrrd_statusExampleParms(HostExample example) {
	Map parms = new HashMap();
	switch (example.getRrdStatus_Indicator()) {
	case HostExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_NULL", "Y");
	    } else {
		parms.put("AND_rrd_status_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_NOT_NULL", "Y");
	    } else {
		parms.put("AND_rrd_status_NOT_NULL", "Y");
	    }
	    break;
	case HostExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_EQUALS", "Y");
	    } else {
		parms.put("AND_rrd_status_EQUALS", "Y");
	    }
	    parms.put("rrdStatus", example.getRrdStatus());
	    break;
	case HostExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_rrd_status_NOT_EQUALS", "Y");
	    }
	    parms.put("rrdStatus", example.getRrdStatus());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_GT", "Y");
	    } else {
		parms.put("AND_rrd_status_GT", "Y");
	    }
	    parms.put("rrdStatus", example.getRrdStatus());
	    break;
	case HostExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_GE", "Y");
	    } else {
		parms.put("AND_rrd_status_GE", "Y");
	    }
	    parms.put("rrdStatus", example.getRrdStatus());
	    break;
	case HostExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_LT", "Y");
	    } else {
		parms.put("AND_rrd_status_LT", "Y");
	    }
	    parms.put("rrdStatus", example.getRrdStatus());
	    break;
	case HostExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_rrd_status_LE", "Y");
	    } else {
		parms.put("AND_rrd_status_LE", "Y");
	    }
	    parms.put("rrdStatus", example.getRrdStatus());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getExampleParms(HostExample example) {
	Map parms = new HashMap();
	parms.putAll(gethost_idExampleParms(example));
	parms.putAll(getgroup_idExampleParms(example));
	parms.putAll(gethost_nameExampleParms(example));
	parms.putAll(gethost_ipExampleParms(example));
	parms.putAll(getlogin_nameExampleParms(example));
	parms.putAll(getlogin_pwdExampleParms(example));
	parms.putAll(getdiskPartitionExampleParms(example));
	parms.putAll(getuptimeExampleParms(example));
	parms.putAll(getdescriptionExampleParms(example));
	parms.putAll(getvalidateExampleParms(example));
	parms.putAll(getinput_timeExampleParms(example));
	parms.putAll(getupdate_timeExampleParms(example));
	parms.putAll(getrrd_statusExampleParms(example));
	return parms;
    }
}