package cn.livedoor.security.sysguard.domain;

public class DataInfoKey {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info.host_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer hostId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info.type_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer typeId;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info.host_id
     * @return  the value of data_info.host_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getHostId() {
	return hostId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info.host_id
     * @param hostId  the value for data_info.host_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setHostId(Integer hostId) {
	this.hostId = hostId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info.type_id
     * @return  the value of data_info.type_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getTypeId() {
	return typeId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info.type_id
     * @param typeId  the value for data_info.type_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setTypeId(Integer typeId) {
	this.typeId = typeId;
    }
}