package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class Host {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.host_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer hostId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.group_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer groupId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.host_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String hostName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.host_ip
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String hostIp;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.login_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String loginName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.login_pwd
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String loginPwd;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.diskPartition
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String diskpartition;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.uptime
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String uptime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String description;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.validate
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Byte validate;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Date inputTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.update_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Date updateTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host.rrd_status
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Byte rrdStatus;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.host_id
     * @return  the value of host.host_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getHostId() {
	return hostId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.host_id
     * @param hostId  the value for host.host_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setHostId(Integer hostId) {
	this.hostId = hostId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.group_id
     * @return  the value of host.group_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getGroupId() {
	return groupId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.group_id
     * @param groupId  the value for host.group_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setGroupId(Integer groupId) {
	this.groupId = groupId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.host_name
     * @return  the value of host.host_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getHostName() {
	return hostName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.host_name
     * @param hostName  the value for host.host_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setHostName(String hostName) {
	this.hostName = hostName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.host_ip
     * @return  the value of host.host_ip
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getHostIp() {
	return hostIp;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.host_ip
     * @param hostIp  the value for host.host_ip
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setHostIp(String hostIp) {
	this.hostIp = hostIp;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.login_name
     * @return  the value of host.login_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getLoginName() {
	return loginName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.login_name
     * @param loginName  the value for host.login_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setLoginName(String loginName) {
	this.loginName = loginName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.login_pwd
     * @return  the value of host.login_pwd
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getLoginPwd() {
	return loginPwd;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.login_pwd
     * @param loginPwd  the value for host.login_pwd
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setLoginPwd(String loginPwd) {
	this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.diskPartition
     * @return  the value of host.diskPartition
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getDiskpartition() {
	return diskpartition;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.diskPartition
     * @param diskpartition  the value for host.diskPartition
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setDiskpartition(String diskpartition) {
	this.diskpartition = diskpartition;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.uptime
     * @return  the value of host.uptime
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getUptime() {
	return uptime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.uptime
     * @param uptime  the value for host.uptime
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setUptime(String uptime) {
	this.uptime = uptime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.description
     * @return  the value of host.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getDescription() {
	return description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.description
     * @param description  the value for host.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setDescription(String description) {
	this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.validate
     * @return  the value of host.validate
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Byte getValidate() {
	return validate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.validate
     * @param validate  the value for host.validate
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setValidate(Byte validate) {
	this.validate = validate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.input_time
     * @return  the value of host.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.input_time
     * @param inputTime  the value for host.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.update_time
     * @return  the value of host.update_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Date getUpdateTime() {
	return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.update_time
     * @param updateTime  the value for host.update_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setUpdateTime(Date updateTime) {
	this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host.rrd_status
     * @return  the value of host.rrd_status
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Byte getRrdStatus() {
	return rrdStatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host.rrd_status
     * @param rrdStatus  the value for host.rrd_status
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setRrdStatus(Byte rrdStatus) {
	this.rrdStatus = rrdStatus;
    }
}