package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class Role {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column role.role_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer roleId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column role.name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String name;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column role.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String description;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column role.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Date inputTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column role.role_id
     * @return  the value of role.role_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getRoleId() {
	return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column role.role_id
     * @param roleId  the value for role.role_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setRoleId(Integer roleId) {
	this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column role.name
     * @return  the value of role.name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getName() {
	return name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column role.name
     * @param name  the value for role.name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setName(String name) {
	this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column role.description
     * @return  the value of role.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getDescription() {
	return description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column role.description
     * @param description  the value for role.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setDescription(String description) {
	this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column role.input_time
     * @return  the value of role.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column role.input_time
     * @param inputTime  the value for role.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }
}