package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.Role;
import cn.livedoor.security.sysguard.domain.RoleExample;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RoleDAOImpl extends SqlMapDaoTemplate implements RoleDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public RoleDAOImpl(DaoManager daoManager) {
	super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void insert(Role record) {
	insert("role.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKey(Role record) {
	int rows = update("role.abatorgenerated_updateByPrimaryKey", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKeySelective(Role record) {
	int rows = update("role.abatorgenerated_updateByPrimaryKeySelective", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(RoleExample example, String orderByClause) {
	Map parms = getExampleParms(example);
	if (orderByClause != null) {
	    parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
	}
	List list = queryForList("role.abatorgenerated_selectByExample", parms);
	return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(RoleExample example) {
	return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Role selectByPrimaryKey(Integer roleId) {
	Role key = new Role();
	key.setRoleId(roleId);
	Role record = (Role) queryForObject("role.abatorgenerated_selectByPrimaryKey", key);
	return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByExample(RoleExample example) {
	int rows = delete("role.abatorgenerated_deleteByExample", getExampleParms(example));
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByPrimaryKey(Integer roleId) {
	Role key = new Role();
	key.setRoleId(roleId);
	int rows = delete("role.abatorgenerated_deleteByPrimaryKey", key);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getrole_idExampleParms(RoleExample example) {
	Map parms = new HashMap();
	switch (example.getRoleId_Indicator()) {
	case RoleExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_NULL", "Y");
	    } else {
		parms.put("AND_role_id_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_role_id_NOT_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_EQUALS", "Y");
	    } else {
		parms.put("AND_role_id_EQUALS", "Y");
	    }
	    parms.put("roleId", example.getRoleId());
	    break;
	case RoleExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_role_id_NOT_EQUALS", "Y");
	    }
	    parms.put("roleId", example.getRoleId());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_GT", "Y");
	    } else {
		parms.put("AND_role_id_GT", "Y");
	    }
	    parms.put("roleId", example.getRoleId());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_GE", "Y");
	    } else {
		parms.put("AND_role_id_GE", "Y");
	    }
	    parms.put("roleId", example.getRoleId());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_LT", "Y");
	    } else {
		parms.put("AND_role_id_LT", "Y");
	    }
	    parms.put("roleId", example.getRoleId());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_role_id_LE", "Y");
	    } else {
		parms.put("AND_role_id_LE", "Y");
	    }
	    parms.put("roleId", example.getRoleId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getnameExampleParms(RoleExample example) {
	Map parms = new HashMap();
	switch (example.getName_Indicator()) {
	case RoleExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_NULL", "Y");
	    } else {
		parms.put("AND_name_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_name_NOT_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_EQUALS", "Y");
	    } else {
		parms.put("AND_name_EQUALS", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	case RoleExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_name_NOT_EQUALS", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_GT", "Y");
	    } else {
		parms.put("AND_name_GT", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_GE", "Y");
	    } else {
		parms.put("AND_name_GE", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_LT", "Y");
	    } else {
		parms.put("AND_name_LT", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_LE", "Y");
	    } else {
		parms.put("AND_name_LE", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	case RoleExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_name_LIKE", "Y");
	    } else {
		parms.put("AND_name_LIKE", "Y");
	    }
	    parms.put("name", example.getName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getdescriptionExampleParms(RoleExample example) {
	Map parms = new HashMap();
	switch (example.getDescription_Indicator()) {
	case RoleExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NULL", "Y");
	    } else {
		parms.put("AND_description_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_NULL", "Y");
	    } else {
		parms.put("AND_description_NOT_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_EQUALS", "Y");
	    } else {
		parms.put("AND_description_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case RoleExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_description_NOT_EQUALS", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GT", "Y");
	    } else {
		parms.put("AND_description_GT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_GE", "Y");
	    } else {
		parms.put("AND_description_GE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LT", "Y");
	    } else {
		parms.put("AND_description_LT", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LE", "Y");
	    } else {
		parms.put("AND_description_LE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	case RoleExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_description_LIKE", "Y");
	    } else {
		parms.put("AND_description_LIKE", "Y");
	    }
	    parms.put("description", example.getDescription());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getinput_timeExampleParms(RoleExample example) {
	Map parms = new HashMap();
	switch (example.getInputTime_Indicator()) {
	case RoleExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NOT_NULL", "Y");
	    }
	    break;
	case RoleExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case RoleExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_NOT_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GT", "Y");
	    } else {
		parms.put("AND_input_time_GT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case RoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GE", "Y");
	    } else {
		parms.put("AND_input_time_GE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LT", "Y");
	    } else {
		parms.put("AND_input_time_LT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case RoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LE", "Y");
	    } else {
		parms.put("AND_input_time_LE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table role
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getExampleParms(RoleExample example) {
	Map parms = new HashMap();
	parms.putAll(getrole_idExampleParms(example));
	parms.putAll(getnameExampleParms(example));
	parms.putAll(getdescriptionExampleParms(example));
	parms.putAll(getinput_timeExampleParms(example));
	return parms;
    }
}