package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class DataInfo extends DataInfoKey {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info.value1
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String value1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info.value2
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String value2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info.value3
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String value3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Date inputTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info.value1
     * @return  the value of data_info.value1
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getValue1() {
	return value1;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info.value1
     * @param value1  the value for data_info.value1
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setValue1(String value1) {
	this.value1 = value1;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info.value2
     * @return  the value of data_info.value2
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getValue2() {
	return value2;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info.value2
     * @param value2  the value for data_info.value2
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setValue2(String value2) {
	this.value2 = value2;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info.value3
     * @return  the value of data_info.value3
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getValue3() {
	return value3;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info.value3
     * @param value3  the value for data_info.value3
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setValue3(String value3) {
	this.value3 = value3;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info.input_time
     * @return  the value of data_info.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info.input_time
     * @param inputTime  the value for data_info.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }
}