package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class HostGroup {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host_group.group_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer groupId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host_group.os_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Integer osId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host_group.group_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String groupName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host_group.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private String description;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column host_group.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    private Date inputTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host_group.group_id
     * @return  the value of host_group.group_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getGroupId() {
	return groupId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host_group.group_id
     * @param groupId  the value for host_group.group_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setGroupId(Integer groupId) {
	this.groupId = groupId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host_group.os_id
     * @return  the value of host_group.os_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Integer getOsId() {
	return osId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host_group.os_id
     * @param osId  the value for host_group.os_id
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setOsId(Integer osId) {
	this.osId = osId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host_group.group_name
     * @return  the value of host_group.group_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getGroupName() {
	return groupName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host_group.group_name
     * @param groupName  the value for host_group.group_name
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setGroupName(String groupName) {
	this.groupName = groupName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host_group.description
     * @return  the value of host_group.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public String getDescription() {
	return description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host_group.description
     * @param description  the value for host_group.description
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setDescription(String description) {
	this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column host_group.input_time
     * @return  the value of host_group.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column host_group.input_time
     * @param inputTime  the value for host_group.input_time
     * @abatorgenerated  Tue Oct 24 09:57:29 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }
}