package cn.livedoor.security.sysguard.domain;

public class HostExample extends Host {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int hostId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int groupId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int hostName_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int hostIp_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int loginName_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int loginPwd_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int diskpartition_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int uptime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int description_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int validate_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int inputTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int updateTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int rrdStatus_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getHostId_Indicator() {
	return hostId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setHostId_Indicator(int hostId_Indicator) {
	this.hostId_Indicator = hostId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getGroupId_Indicator() {
	return groupId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setGroupId_Indicator(int groupId_Indicator) {
	this.groupId_Indicator = groupId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getHostName_Indicator() {
	return hostName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setHostName_Indicator(int hostName_Indicator) {
	this.hostName_Indicator = hostName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getHostIp_Indicator() {
	return hostIp_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setHostIp_Indicator(int hostIp_Indicator) {
	this.hostIp_Indicator = hostIp_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLoginName_Indicator() {
	return loginName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLoginName_Indicator(int loginName_Indicator) {
	this.loginName_Indicator = loginName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLoginPwd_Indicator() {
	return loginPwd_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLoginPwd_Indicator(int loginPwd_Indicator) {
	this.loginPwd_Indicator = loginPwd_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getDiskpartition_Indicator() {
	return diskpartition_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setDiskpartition_Indicator(int diskpartition_Indicator) {
	this.diskpartition_Indicator = diskpartition_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getUptime_Indicator() {
	return uptime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUptime_Indicator(int uptime_Indicator) {
	this.uptime_Indicator = uptime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getDescription_Indicator() {
	return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setDescription_Indicator(int description_Indicator) {
	this.description_Indicator = description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getValidate_Indicator() {
	return validate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setValidate_Indicator(int validate_Indicator) {
	this.validate_Indicator = validate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getInputTime_Indicator() {
	return inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime_Indicator(int inputTime_Indicator) {
	this.inputTime_Indicator = inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getUpdateTime_Indicator() {
	return updateTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUpdateTime_Indicator(int updateTime_Indicator) {
	this.updateTime_Indicator = updateTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getRrdStatus_Indicator() {
	return rrdStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table host
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setRrdStatus_Indicator(int rrdStatus_Indicator) {
	this.rrdStatus_Indicator = rrdStatus_Indicator;
    }
}