package cn.livedoor.security.sysguard.domain;

public class OsTypeExample extends OsType {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int osId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int osName_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int description_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int inputTime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getOsId_Indicator() {
	return osId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOsId_Indicator(int osId_Indicator) {
	this.osId_Indicator = osId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getOsName_Indicator() {
	return osName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOsName_Indicator(int osName_Indicator) {
	this.osName_Indicator = osName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getDescription_Indicator() {
	return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setDescription_Indicator(int description_Indicator) {
	this.description_Indicator = description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getInputTime_Indicator() {
	return inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table os_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime_Indicator(int inputTime_Indicator) {
	this.inputTime_Indicator = inputTime_Indicator;
    }
}