package cn.livedoor.security.sysguard.domain;

public class UserExample extends User {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int userId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int roleId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int name_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int realName_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int passwd_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int mail_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int msn_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int skype_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int lastLoginTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int online_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int validate_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int inputTime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int updateTime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getUserId_Indicator() {
	return userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUserId_Indicator(int userId_Indicator) {
	this.userId_Indicator = userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getRoleId_Indicator() {
	return roleId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setRoleId_Indicator(int roleId_Indicator) {
	this.roleId_Indicator = roleId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getName_Indicator() {
	return name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setName_Indicator(int name_Indicator) {
	this.name_Indicator = name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getRealName_Indicator() {
	return realName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setRealName_Indicator(int realName_Indicator) {
	this.realName_Indicator = realName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getPasswd_Indicator() {
	return passwd_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setPasswd_Indicator(int passwd_Indicator) {
	this.passwd_Indicator = passwd_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getMail_Indicator() {
	return mail_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setMail_Indicator(int mail_Indicator) {
	this.mail_Indicator = mail_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getMsn_Indicator() {
	return msn_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setMsn_Indicator(int msn_Indicator) {
	this.msn_Indicator = msn_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getSkype_Indicator() {
	return skype_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setSkype_Indicator(int skype_Indicator) {
	this.skype_Indicator = skype_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getLastLoginTime_Indicator() {
	return lastLoginTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setLastLoginTime_Indicator(int lastLoginTime_Indicator) {
	this.lastLoginTime_Indicator = lastLoginTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getOnline_Indicator() {
	return online_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOnline_Indicator(int online_Indicator) {
	this.online_Indicator = online_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getValidate_Indicator() {
	return validate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setValidate_Indicator(int validate_Indicator) {
	this.validate_Indicator = validate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getInputTime_Indicator() {
	return inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime_Indicator(int inputTime_Indicator) {
	this.inputTime_Indicator = inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getUpdateTime_Indicator() {
	return updateTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table user
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUpdateTime_Indicator(int updateTime_Indicator) {
	this.updateTime_Indicator = updateTime_Indicator;
    }
}