package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.Applog;
import cn.livedoor.security.sysguard.domain.ApplogExample;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ApplogDAOImpl extends SqlMapDaoTemplate implements ApplogDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public ApplogDAOImpl(DaoManager daoManager) {
	super(daoManager);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void insert(Applog record) {
	insert("applog.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKey(Applog record) {
	int rows = update("applog.abatorgenerated_updateByPrimaryKey", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int updateByPrimaryKeySelective(Applog record) {
	int rows = update("applog.abatorgenerated_updateByPrimaryKeySelective", record);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(ApplogExample example, String orderByClause) {
	Map parms = getExampleParms(example);
	if (orderByClause != null) {
	    parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
	}
	List list = queryForList("applog.abatorgenerated_selectByExample", parms);
	return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public List selectByExample(ApplogExample example) {
	return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Applog selectByPrimaryKey(Long applogId) {
	Applog key = new Applog();
	key.setApplogId(applogId);
	Applog record = (Applog) queryForObject("applog.abatorgenerated_selectByPrimaryKey", key);
	return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByExample(ApplogExample example) {
	int rows = delete("applog.abatorgenerated_deleteByExample", getExampleParms(example));
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int deleteByPrimaryKey(Long applogId) {
	Applog key = new Applog();
	key.setApplogId(applogId);
	int rows = delete("applog.abatorgenerated_deleteByPrimaryKey", key);
	return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getapplog_idExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getApplogId_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_NULL", "Y");
	    } else {
		parms.put("AND_applog_id_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_applog_id_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_EQUALS", "Y");
	    } else {
		parms.put("AND_applog_id_EQUALS", "Y");
	    }
	    parms.put("applogId", example.getApplogId());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_applog_id_NOT_EQUALS", "Y");
	    }
	    parms.put("applogId", example.getApplogId());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_GT", "Y");
	    } else {
		parms.put("AND_applog_id_GT", "Y");
	    }
	    parms.put("applogId", example.getApplogId());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_GE", "Y");
	    } else {
		parms.put("AND_applog_id_GE", "Y");
	    }
	    parms.put("applogId", example.getApplogId());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_LT", "Y");
	    } else {
		parms.put("AND_applog_id_LT", "Y");
	    }
	    parms.put("applogId", example.getApplogId());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_applog_id_LE", "Y");
	    } else {
		parms.put("AND_applog_id_LE", "Y");
	    }
	    parms.put("applogId", example.getApplogId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getuser_idExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getUserId_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_NULL", "Y");
	    } else {
		parms.put("AND_user_id_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_user_id_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_EQUALS", "Y");
	    } else {
		parms.put("AND_user_id_EQUALS", "Y");
	    }
	    parms.put("userId", example.getUserId());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_user_id_NOT_EQUALS", "Y");
	    }
	    parms.put("userId", example.getUserId());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_GT", "Y");
	    } else {
		parms.put("AND_user_id_GT", "Y");
	    }
	    parms.put("userId", example.getUserId());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_GE", "Y");
	    } else {
		parms.put("AND_user_id_GE", "Y");
	    }
	    parms.put("userId", example.getUserId());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_LT", "Y");
	    } else {
		parms.put("AND_user_id_LT", "Y");
	    }
	    parms.put("userId", example.getUserId());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_user_id_LE", "Y");
	    } else {
		parms.put("AND_user_id_LE", "Y");
	    }
	    parms.put("userId", example.getUserId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map gethost_idExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getHostId_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NULL", "Y");
	    } else {
		parms.put("AND_host_id_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NOT_NULL", "Y");
	    } else {
		parms.put("AND_host_id_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_EQUALS", "Y");
	    } else {
		parms.put("AND_host_id_EQUALS", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_host_id_NOT_EQUALS", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_GT", "Y");
	    } else {
		parms.put("AND_host_id_GT", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_GE", "Y");
	    } else {
		parms.put("AND_host_id_GE", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_LT", "Y");
	    } else {
		parms.put("AND_host_id_LT", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_host_id_LE", "Y");
	    } else {
		parms.put("AND_host_id_LE", "Y");
	    }
	    parms.put("hostId", example.getHostId());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlevelExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getLevel_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_NULL", "Y");
	    } else {
		parms.put("AND_level_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_NOT_NULL", "Y");
	    } else {
		parms.put("AND_level_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_EQUALS", "Y");
	    } else {
		parms.put("AND_level_EQUALS", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_level_NOT_EQUALS", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_GT", "Y");
	    } else {
		parms.put("AND_level_GT", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_GE", "Y");
	    } else {
		parms.put("AND_level_GE", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_LT", "Y");
	    } else {
		parms.put("AND_level_LT", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_LE", "Y");
	    } else {
		parms.put("AND_level_LE", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_level_LIKE", "Y");
	    } else {
		parms.put("AND_level_LIKE", "Y");
	    }
	    parms.put("level", example.getLevel());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getuptimeExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getUptime_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_NULL", "Y");
	    } else {
		parms.put("AND_uptime_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_NOT_NULL", "Y");
	    } else {
		parms.put("AND_uptime_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_EQUALS", "Y");
	    } else {
		parms.put("AND_uptime_EQUALS", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_uptime_NOT_EQUALS", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_GT", "Y");
	    } else {
		parms.put("AND_uptime_GT", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_GE", "Y");
	    } else {
		parms.put("AND_uptime_GE", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_LT", "Y");
	    } else {
		parms.put("AND_uptime_LT", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_uptime_LE", "Y");
	    } else {
		parms.put("AND_uptime_LE", "Y");
	    }
	    parms.put("uptime", example.getUptime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getclass_nameExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getClassName_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_NULL", "Y");
	    } else {
		parms.put("AND_class_name_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_class_name_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_EQUALS", "Y");
	    } else {
		parms.put("AND_class_name_EQUALS", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_class_name_NOT_EQUALS", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_GT", "Y");
	    } else {
		parms.put("AND_class_name_GT", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_GE", "Y");
	    } else {
		parms.put("AND_class_name_GE", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_LT", "Y");
	    } else {
		parms.put("AND_class_name_LT", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_LE", "Y");
	    } else {
		parms.put("AND_class_name_LE", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_class_name_LIKE", "Y");
	    } else {
		parms.put("AND_class_name_LIKE", "Y");
	    }
	    parms.put("className", example.getClassName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getthread_nameExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getThreadName_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_NULL", "Y");
	    } else {
		parms.put("AND_thread_name_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_NOT_NULL", "Y");
	    } else {
		parms.put("AND_thread_name_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_EQUALS", "Y");
	    } else {
		parms.put("AND_thread_name_EQUALS", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_thread_name_NOT_EQUALS", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_GT", "Y");
	    } else {
		parms.put("AND_thread_name_GT", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_GE", "Y");
	    } else {
		parms.put("AND_thread_name_GE", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_LT", "Y");
	    } else {
		parms.put("AND_thread_name_LT", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_LE", "Y");
	    } else {
		parms.put("AND_thread_name_LE", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_thread_name_LIKE", "Y");
	    } else {
		parms.put("AND_thread_name_LIKE", "Y");
	    }
	    parms.put("threadName", example.getThreadName());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlog_timeExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getLogTime_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_NULL", "Y");
	    } else {
		parms.put("AND_log_time_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_log_time_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_EQUALS", "Y");
	    } else {
		parms.put("AND_log_time_EQUALS", "Y");
	    }
	    parms.put("logTime", example.getLogTime());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_log_time_NOT_EQUALS", "Y");
	    }
	    parms.put("logTime", example.getLogTime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_GT", "Y");
	    } else {
		parms.put("AND_log_time_GT", "Y");
	    }
	    parms.put("logTime", example.getLogTime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_GE", "Y");
	    } else {
		parms.put("AND_log_time_GE", "Y");
	    }
	    parms.put("logTime", example.getLogTime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_LT", "Y");
	    } else {
		parms.put("AND_log_time_LT", "Y");
	    }
	    parms.put("logTime", example.getLogTime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_time_LE", "Y");
	    } else {
		parms.put("AND_log_time_LE", "Y");
	    }
	    parms.put("logTime", example.getLogTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlog_lineExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getLogLine_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_NULL", "Y");
	    } else {
		parms.put("AND_log_line_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_NOT_NULL", "Y");
	    } else {
		parms.put("AND_log_line_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_EQUALS", "Y");
	    } else {
		parms.put("AND_log_line_EQUALS", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_log_line_NOT_EQUALS", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_GT", "Y");
	    } else {
		parms.put("AND_log_line_GT", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_GE", "Y");
	    } else {
		parms.put("AND_log_line_GE", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_LT", "Y");
	    } else {
		parms.put("AND_log_line_LT", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_LE", "Y");
	    } else {
		parms.put("AND_log_line_LE", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_line_LIKE", "Y");
	    } else {
		parms.put("AND_log_line_LIKE", "Y");
	    }
	    parms.put("logLine", example.getLogLine());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlog_contentExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getLogContent_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_NULL", "Y");
	    } else {
		parms.put("AND_log_content_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_NOT_NULL", "Y");
	    } else {
		parms.put("AND_log_content_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_EQUALS", "Y");
	    } else {
		parms.put("AND_log_content_EQUALS", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_log_content_NOT_EQUALS", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_GT", "Y");
	    } else {
		parms.put("AND_log_content_GT", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_GE", "Y");
	    } else {
		parms.put("AND_log_content_GE", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_LT", "Y");
	    } else {
		parms.put("AND_log_content_LT", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_LE", "Y");
	    } else {
		parms.put("AND_log_content_LE", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_content_LIKE", "Y");
	    } else {
		parms.put("AND_log_content_LIKE", "Y");
	    }
	    parms.put("logContent", example.getLogContent());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getlog_statusExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getLogStatus_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_NULL", "Y");
	    } else {
		parms.put("AND_log_status_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_NOT_NULL", "Y");
	    } else {
		parms.put("AND_log_status_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_EQUALS", "Y");
	    } else {
		parms.put("AND_log_status_EQUALS", "Y");
	    }
	    parms.put("logStatus", example.getLogStatus());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_log_status_NOT_EQUALS", "Y");
	    }
	    parms.put("logStatus", example.getLogStatus());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_GT", "Y");
	    } else {
		parms.put("AND_log_status_GT", "Y");
	    }
	    parms.put("logStatus", example.getLogStatus());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_GE", "Y");
	    } else {
		parms.put("AND_log_status_GE", "Y");
	    }
	    parms.put("logStatus", example.getLogStatus());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_LT", "Y");
	    } else {
		parms.put("AND_log_status_LT", "Y");
	    }
	    parms.put("logStatus", example.getLogStatus());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_log_status_LE", "Y");
	    } else {
		parms.put("AND_log_status_LE", "Y");
	    }
	    parms.put("logStatus", example.getLogStatus());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getsolve_timeExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getSolveTime_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_NULL", "Y");
	    } else {
		parms.put("AND_solve_time_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_solve_time_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_EQUALS", "Y");
	    } else {
		parms.put("AND_solve_time_EQUALS", "Y");
	    }
	    parms.put("solveTime", example.getSolveTime());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_solve_time_NOT_EQUALS", "Y");
	    }
	    parms.put("solveTime", example.getSolveTime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_GT", "Y");
	    } else {
		parms.put("AND_solve_time_GT", "Y");
	    }
	    parms.put("solveTime", example.getSolveTime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_GE", "Y");
	    } else {
		parms.put("AND_solve_time_GE", "Y");
	    }
	    parms.put("solveTime", example.getSolveTime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_LT", "Y");
	    } else {
		parms.put("AND_solve_time_LT", "Y");
	    }
	    parms.put("solveTime", example.getSolveTime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_time_LE", "Y");
	    } else {
		parms.put("AND_solve_time_LE", "Y");
	    }
	    parms.put("solveTime", example.getSolveTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getsolve_resultExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getSolveResult_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_NULL", "Y");
	    } else {
		parms.put("AND_solve_result_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_NOT_NULL", "Y");
	    } else {
		parms.put("AND_solve_result_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_EQUALS", "Y");
	    } else {
		parms.put("AND_solve_result_EQUALS", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_solve_result_NOT_EQUALS", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_GT", "Y");
	    } else {
		parms.put("AND_solve_result_GT", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_GE", "Y");
	    } else {
		parms.put("AND_solve_result_GE", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_LT", "Y");
	    } else {
		parms.put("AND_solve_result_LT", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_LE", "Y");
	    } else {
		parms.put("AND_solve_result_LE", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_result_LIKE", "Y");
	    } else {
		parms.put("AND_solve_result_LIKE", "Y");
	    }
	    parms.put("solveResult", example.getSolveResult());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getsolve_descExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getSolveDesc_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_NULL", "Y");
	    } else {
		parms.put("AND_solve_desc_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_NOT_NULL", "Y");
	    } else {
		parms.put("AND_solve_desc_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_EQUALS", "Y");
	    } else {
		parms.put("AND_solve_desc_EQUALS", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_solve_desc_NOT_EQUALS", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_GT", "Y");
	    } else {
		parms.put("AND_solve_desc_GT", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_GE", "Y");
	    } else {
		parms.put("AND_solve_desc_GE", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_LT", "Y");
	    } else {
		parms.put("AND_solve_desc_LT", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_LE", "Y");
	    } else {
		parms.put("AND_solve_desc_LE", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	case ApplogExample.EXAMPLE_LIKE:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_solve_desc_LIKE", "Y");
	    } else {
		parms.put("AND_solve_desc_LIKE", "Y");
	    }
	    parms.put("solveDesc", example.getSolveDesc());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getinput_timeExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	switch (example.getInputTime_Indicator()) {
	case ApplogExample.EXAMPLE_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_NOT_NULL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_NULL", "Y");
	    } else {
		parms.put("AND_input_time_NOT_NULL", "Y");
	    }
	    break;
	case ApplogExample.EXAMPLE_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case ApplogExample.EXAMPLE_NOT_EQUALS:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_NOT_EQUALS", "Y");
	    } else {
		parms.put("AND_input_time_NOT_EQUALS", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GT", "Y");
	    } else {
		parms.put("AND_input_time_GT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case ApplogExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_GE", "Y");
	    } else {
		parms.put("AND_input_time_GE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LT", "Y");
	    } else {
		parms.put("AND_input_time_LT", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	case ApplogExample.EXAMPLE_LESS_THAN_OR_EQUAL:
	    if (example.isCombineTypeOr()) {
		parms.put("OR_input_time_LE", "Y");
	    } else {
		parms.put("AND_input_time_LE", "Y");
	    }
	    parms.put("inputTime", example.getInputTime());
	    break;
	}
	return parms;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Map getExampleParms(ApplogExample example) {
	Map parms = new HashMap();
	parms.putAll(getapplog_idExampleParms(example));
	parms.putAll(getuser_idExampleParms(example));
	parms.putAll(gethost_idExampleParms(example));
	parms.putAll(getlevelExampleParms(example));
	parms.putAll(getuptimeExampleParms(example));
	parms.putAll(getclass_nameExampleParms(example));
	parms.putAll(getthread_nameExampleParms(example));
	parms.putAll(getlog_timeExampleParms(example));
	parms.putAll(getlog_lineExampleParms(example));
	parms.putAll(getlog_contentExampleParms(example));
	parms.putAll(getlog_statusExampleParms(example));
	parms.putAll(getsolve_timeExampleParms(example));
	parms.putAll(getsolve_resultExampleParms(example));
	parms.putAll(getsolve_descExampleParms(example));
	parms.putAll(getinput_timeExampleParms(example));
	return parms;
    }
}