package cn.livedoor.security.sysguard.persistence.sqlmapdao;

import cn.livedoor.security.sysguard.domain.Applog;
import cn.livedoor.security.sysguard.domain.ApplogExample;
import java.util.List;

public interface ApplogDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    void insert(Applog record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    int updateByPrimaryKey(Applog record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    int updateByPrimaryKeySelective(Applog record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    List selectByExample(ApplogExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    List selectByExample(ApplogExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    Applog selectByPrimaryKey(Long applogId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    int deleteByExample(ApplogExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table applog
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    int deleteByPrimaryKey(Long applogId);
}