package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class Operation {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column operation.oper_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer operId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column operation.user_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer userId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column operation.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Date inputTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column operation.oper_id
     * @return  the value of operation.oper_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getOperId() {
	return operId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column operation.oper_id
     * @param operId  the value for operation.oper_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setOperId(Integer operId) {
	this.operId = operId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column operation.user_id
     * @return  the value of operation.user_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getUserId() {
	return userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column operation.user_id
     * @param userId  the value for operation.user_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setUserId(Integer userId) {
	this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column operation.input_time
     * @return  the value of operation.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column operation.input_time
     * @param inputTime  the value for operation.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }
}