package cn.livedoor.security.sysguard.domain;

public class DataInfoTypeExample extends DataInfoType {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int typeId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int typeName_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int warnValue_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int errorValue_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int dataCommand_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int inputTime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getTypeId_Indicator() {
	return typeId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setTypeId_Indicator(int typeId_Indicator) {
	this.typeId_Indicator = typeId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getTypeName_Indicator() {
	return typeName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setTypeName_Indicator(int typeName_Indicator) {
	this.typeName_Indicator = typeName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getWarnValue_Indicator() {
	return warnValue_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setWarnValue_Indicator(int warnValue_Indicator) {
	this.warnValue_Indicator = warnValue_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getErrorValue_Indicator() {
	return errorValue_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setErrorValue_Indicator(int errorValue_Indicator) {
	this.errorValue_Indicator = errorValue_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getDataCommand_Indicator() {
	return dataCommand_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setDataCommand_Indicator(int dataCommand_Indicator) {
	this.dataCommand_Indicator = dataCommand_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getInputTime_Indicator() {
	return inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info_type
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime_Indicator(int inputTime_Indicator) {
	this.inputTime_Indicator = inputTime_Indicator;
    }
}