package cn.livedoor.security.sysguard.domain;

public class DataInfoExample extends DataInfo {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int hostId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int typeId_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int value1_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int value2_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int value3_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private int inputTime_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getHostId_Indicator() {
	return hostId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setHostId_Indicator(int hostId_Indicator) {
	this.hostId_Indicator = hostId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getTypeId_Indicator() {
	return typeId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setTypeId_Indicator(int typeId_Indicator) {
	this.typeId_Indicator = typeId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getValue1_Indicator() {
	return value1_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setValue1_Indicator(int value1_Indicator) {
	this.value1_Indicator = value1_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getValue2_Indicator() {
	return value2_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setValue2_Indicator(int value2_Indicator) {
	this.value2_Indicator = value2_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getValue3_Indicator() {
	return value3_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setValue3_Indicator(int value3_Indicator) {
	this.value3_Indicator = value3_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public int getInputTime_Indicator() {
	return inputTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table data_info
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime_Indicator(int inputTime_Indicator) {
	this.inputTime_Indicator = inputTime_Indicator;
    }
}