package cn.livedoor.security.sysguard.domain;

import java.util.Date;

public class DataInfoType {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info_type.type_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer typeId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info_type.type_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String typeName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info_type.warn_value
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer warnValue;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info_type.error_value
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Integer errorValue;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info_type.data_command
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private String dataCommand;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column data_info_type.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    private Date inputTime;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info_type.type_id
     * @return  the value of data_info_type.type_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getTypeId() {
	return typeId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info_type.type_id
     * @param typeId  the value for data_info_type.type_id
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setTypeId(Integer typeId) {
	this.typeId = typeId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info_type.type_name
     * @return  the value of data_info_type.type_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getTypeName() {
	return typeName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info_type.type_name
     * @param typeName  the value for data_info_type.type_name
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setTypeName(String typeName) {
	this.typeName = typeName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info_type.warn_value
     * @return  the value of data_info_type.warn_value
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getWarnValue() {
	return warnValue;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info_type.warn_value
     * @param warnValue  the value for data_info_type.warn_value
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setWarnValue(Integer warnValue) {
	this.warnValue = warnValue;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info_type.error_value
     * @return  the value of data_info_type.error_value
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Integer getErrorValue() {
	return errorValue;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info_type.error_value
     * @param errorValue  the value for data_info_type.error_value
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setErrorValue(Integer errorValue) {
	this.errorValue = errorValue;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info_type.data_command
     * @return  the value of data_info_type.data_command
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public String getDataCommand() {
	return dataCommand;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info_type.data_command
     * @param dataCommand  the value for data_info_type.data_command
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setDataCommand(String dataCommand) {
	this.dataCommand = dataCommand;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column data_info_type.input_time
     * @return  the value of data_info_type.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public Date getInputTime() {
	return inputTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column data_info_type.input_time
     * @param inputTime  the value for data_info_type.input_time
     * @abatorgenerated  Tue Oct 24 10:06:07 CST 2006
     */
    public void setInputTime(Date inputTime) {
	this.inputTime = inputTime;
    }
}